apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-blue
  labels:
    app: todo-app
    track: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
      track: blue
  template:
    metadata:
      labels:
        app: todo-app
        track: blue
    spec:
      containers:
        - name: todo-app
          image: YOUR_DOCKERHUB_USERNAME/todo-app:blue
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-green
  labels:
    app: todo-app
    track: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
      track: green
  template:
    metadata:
      labels:
        app: todo-app
        track: green
    spec:
      containers:
        - name: todo-app
          image: YOUR_DOCKERHUB_USERNAME/todo-app:green
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  selector:
    app: todo-app
    active: blue # switch to green when you want to point to green deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
